openapi: "3.0.0"
info:
    title: API Title
    version: "1.0.0"
paths:
    /test/{testId}:
        get:
            operationId: GetTest
            parameters:
                - description: Query param
                  name: query
                  in: query
                  required: false
                  schema:
                    type: string
            responses:
                "200":
                    description: Test
                    content:
                        application/json:
                            schema:
                                description: Test schema
                                type: object
                                required:
                                    - id
                                properties:
                                    id:
                                        type: string
                                    paging:
                                        description: Paging section
                                        type: object
                                        properties:
                                            total:
                                                description: Total count
                                                type: integer
                                                example: 439
                "403":
                    description: Forbidden response
                    content:
                        application/json:
                            schema:
                                description: General error structure
                                type: object
                                required:
                                    - errorCode
                                    - requestId
                                properties:
                                    errorCode:
                                        description: ErrCode enumeration
                                        type: string
                                        enum:
                                            - ErrUnknownError
                                            - ErrEntityNotFound
                                    requestId:
                                        type: string
                                    message:
                                        type: string
                            examples:
                                "example1":
                                    value:
                                        errorCode: ErrOperationForbidden
                                        requestId: "x837ant-000007"
                                        message: Forbidden
    /test2:
        get:
            operationId: GetTest2
            responses:
                "200":
                    description: Test
                    content:
                        application/json:
                            schema:
                                description: Paging section
                                type: object
                                properties:
                                    total:
                                        description: Total count
                                        type: integer
                                        example: 439
